steps:
  # ==========================================
  # 1. Build & Push Frontend
  # ==========================================
  - name: 'gcr.io/k8s-skaffold/pack'
    id: 'build-frontend'
    secretEnv: 
      - 'NEXT_PUBLIC_FIREBASE_API_KEY'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID'
      - 'NEXT_PUBLIC_BACKEND_URL'
      # NEXT_PUBLIC_FIREBASE_PROJECT_ID is assumed to match $PROJECT_ID, but we can pull it too if needed.
    args:
      - 'build'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/conthunt-frontend/app'
      - '--builder=gcr.io/buildpacks/builder:google-22'
      - '--trust-builder'
      - '--path=frontend/'
      - '--publish'
      - '--env=NEXT_PUBLIC_FIREBASE_API_KEY'
      - '--env=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
      - '--env=NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID'
      - '--env=NEXT_PUBLIC_FIREBASE_APP_ID'
      - '--env=NEXT_PUBLIC_BACKEND_URL'

  # ==========================================
  # 2. Deploy Frontend
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'conthunt-frontend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/conthunt-frontend/app'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
    env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_BACKEND_URL/versions/latest
    env: 'NEXT_PUBLIC_BACKEND_URL'



options:
  logging: CLOUD_LOGGING_ONLY
