import type { Metadata } from "next";
import Script from "next/script";
import { Plus_Jakarta_Sans, Space_Grotesk, DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { GridTorch } from "@/components/ui/grid-torch";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-main",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-card",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-nav",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Conthunt",
  description: "Generated by create next app",
  icons: {
    icon: "/images/image.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${plusJakartaSans.variable} ${spaceGrotesk.variable} ${dmSans.variable} antialiased bg-background text-foreground`}
      >
        <Script
          src="https://cdn.lordicon.com/lordicon.js"
          strategy="afterInteractive"
        />
        {/* <GridTorch /> */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html >
  );
}
