steps:
  # ==========================================
  # 1. Build & Push Backend
  # ==========================================
  - name: 'gcr.io/k8s-skaffold/pack'
    id: 'build-backend'
    args:
      - 'build'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/conthunt-backend/app'
      - '--builder=gcr.io/buildpacks/builder:google-22'
      - '--trust-builder'
      - '--path=backend/'
      - '--publish'
      - '--env=GOOGLE_ENTRYPOINT=uvicorn app.main:app --host 0.0.0.0 --port 8080'

  # ==========================================
  # 2. Deploy Backend (with ALL Secrets)
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'conthunt'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/conthunt-backend/app'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--network=default'
      - '--subnet=default'
      - '--vpc-egress=private-ranges-only'

      # --set-secrets maps Secret Manager keys to Environment Variables in the container
      # Format: ENV_VAR=SECRET_NAME:VERSION
      - '--set-secrets=APP_ENV=APP_ENV:latest'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest'
      - '--set-secrets=TWELVELABS_API_KEY=TWELVELABS_API_KEY:latest'
      - '--set-secrets=TWELVELABS_INDEX_ID=TWELVELABS_INDEX_ID:latest'
      - '--set-secrets=TWELVELABS_UPLOAD_TIMEOUT=TWELVELABS_UPLOAD_TIMEOUT:latest'
      - '--set-secrets=TWELVELABS_INDEX_TIMEOUT=TWELVELABS_INDEX_TIMEOUT:latest'
      - '--set-secrets=DODO_API_KEY=DODO_API_KEY:latest'
      - '--set-secrets=DODO_WEBHOOK_SECRET=DODO_WEBHOOK_SECRET:latest'
      - '--set-secrets=DODO_ENVIRONMENT=DODO_ENVIRONMENT:latest'
      - '--set-secrets=DODO_BRAND_ID=DODO_BRAND_ID:latest'
      - '--set-secrets=SCRAPECREATORS_API_KEY=SCRAPECREATORS_API_KEY:latest'
      - '--set-secrets=SCRAPECREATORS_BASE_URL=SCRAPECREATORS_BASE_URL:latest'
      - '--set-secrets=GCP_REGION=GCP_REGION:latest'
      - '--set-secrets=GOOGLE_APPLICATION_CREDENTIALS_FB=GOOGLE_APPLICATION_CREDENTIALS_FB:latest'
      - '--set-secrets=REDIS_URL=REDIS_URL:latest'
      - '--set-secrets=REDIS_MAX_CONNECTIONS=REDIS_MAX_CONNECTIONS:latest'
      - '--set-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest'
      - '--set-secrets=OPENAI_BASE_URL=OPENAI_BASE_URL:latest'
      - '--set-secrets=LOG_LEVEL=LOG_LEVEL:latest'
      - '--set-secrets=API_BASE_URL=API_BASE_URL:latest'
      - '--set-secrets=DB_SCHEMA=DB_SCHEMA:latest'
      - '--set-secrets=DB_PGBOUNCER_MODE=DB_PGBOUNCER_MODE:latest'
      - '--set-secrets=DB_USE_NULLPOOL=DB_USE_NULLPOOL:latest'
      - '--set-secrets=DB_SEMAPHORE_ENABLED=DB_SEMAPHORE_ENABLED:latest'
      - '--set-secrets=DB_SEM_KEY_PREFIX=DB_SEM_KEY_PREFIX:latest'
      - '--set-secrets=DB_SEM_TTL_MS=DB_SEM_TTL_MS:latest'
      - '--set-secrets=DB_SEM_API_LIMIT=DB_SEM_API_LIMIT:latest'
      - '--set-secrets=DB_SEM_TASKS_LIMIT=DB_SEM_TASKS_LIMIT:latest'
      - '--set-secrets=DB_SEM_API_MAX_WAIT_MS=DB_SEM_API_MAX_WAIT_MS:latest'
      - '--set-secrets=DB_SEM_TASKS_MAX_WAIT_MS=DB_SEM_TASKS_MAX_WAIT_MS:latest'
      - '--set-secrets=DB_POOL_SIZE=DB_POOL_SIZE:latest'
      - '--set-secrets=DB_MAX_OVERFLOW=DB_MAX_OVERFLOW:latest'
      - '--set-secrets=DB_POOL_TIMEOUT=DB_POOL_TIMEOUT:latest'
      - '--set-secrets=GCS_BUCKET_RAW=GCS_BUCKET_RAW:latest'
      - '--set-secrets=GCS_BUCKET_MEDIA=GCS_BUCKET_MEDIA:latest'
      - '--set-secrets=GCS_DEEPAGNT_FS=GCS_DEEPAGNT_FS:latest'
      - '--set-secrets=GCS_SIGNER_KEY_PATH=GCS_SIGNER_KEY_PATH:latest'
      - '--set-secrets=CDN_SIGNING_KEY_NAME=CDN_SIGNING_KEY_NAME:latest'
      - '--set-secrets=CDN_SIGNING_KEY_VALUE=CDN_SIGNING_KEY_VALUE:latest'
      - '--set-secrets=CDN_URL_PREFIX=CDN_URL_PREFIX:latest'
      - '--set-secrets=CLOUD_TASKS_SA_EMAIL=CLOUD_TASKS_SA_EMAIL:latest'
      - '--set-secrets=QUEUE_MEDIA_DOWNLOAD=QUEUE_MEDIA_DOWNLOAD:latest'
      - '--set-secrets=QUEUE_TWELVELABS=QUEUE_TWELVELABS:latest'
      - '--set-secrets=QUEUE_GEMINI=QUEUE_GEMINI:latest'
      - '--set-secrets=QUEUE_RAW_ARCHIVE=QUEUE_RAW_ARCHIVE:latest'
      - '--set-secrets=QUEUE_MEDIA_DOWNLOAD_PRIORITY=QUEUE_MEDIA_DOWNLOAD_PRIORITY:latest'
      - '--set-secrets=QUEUE_SEARCH_WORKER=QUEUE_SEARCH_WORKER:latest'
      - '--set-secrets=QUEUE_CHAT_STREAM=QUEUE_CHAT_STREAM:latest'
      - '--set-secrets=MEDIA_DOWNLOAD_ENABLED=MEDIA_DOWNLOAD_ENABLED:latest'
      - '--set-secrets=MEDIA_MAX_CONCURRENCY=MEDIA_MAX_CONCURRENCY:latest'
      - '--set-secrets=MEDIA_HTTP_TIMEOUT_S=MEDIA_HTTP_TIMEOUT_S:latest'
      - '--set-secrets=MEDIA_OPTIMIZE_IMAGES=MEDIA_OPTIMIZE_IMAGES:latest'
      - '--set-secrets=MEDIA_IMAGE_FORMAT=MEDIA_IMAGE_FORMAT:latest'
      - '--set-secrets=MEDIA_IMAGE_QUALITY=MEDIA_IMAGE_QUALITY:latest'
      - '--set-secrets=RAW_UPLOAD_ENABLED=RAW_UPLOAD_ENABLED:latest'
      - '--set-secrets=FRONTEND_RETURN_URL=FRONTEND_RETURN_URL:latest'
      - '--set-secrets=OTEL_SERVICE_NAME=OTEL_SERVICE_NAME:latest'
      - '--set-secrets=OTEL_RESOURCE_ATTRIBUTES=OTEL_RESOURCE_ATTRIBUTES:latest'
      - '--set-secrets=SMTP_HOST=SMTP_HOST:latest'
      - '--set-secrets=SMTP_PORT=SMTP_PORT:latest'
      - '--set-secrets=SMTP_USER=SMTP_USER:latest'
      - '--set-secrets=SMTP_PASSWORD=SMTP_PASSWORD:latest'
      - '--set-secrets=SMTP_FROM_EMAIL=SMTP_FROM_EMAIL:latest'
      - '--set-secrets=WHOP_API_KEY=WHOP_API_KEY:latest'
      - '--set-secrets=WHOP_WEBHOOK_SECRET=WHOP_WEBHOOK_SECRET:latest'
      - '--set-secrets=WHOP_APP_ID=WHOP_APP_ID:latest'
      - '--set-secrets=WHOP_COMPANY_ID=WHOP_COMPANY_ID:latest'
      - '--set-secrets=WHOP_PRODUCT_PRO=WHOP_PRODUCT_PRO:latest'
      - '--set-secrets=WHOP_PRODUCT_CREATOR=WHOP_PRODUCT_CREATOR:latest'
      - '--set-secrets=DEEP_RESEARCH_ANALYSIS_CONCURRENCY=DEEP_RESEARCH_ANALYSIS_CONCURRENCY:latest'
      - '--set-secrets=DEEP_RESEARCH_SEARCH_CONCURRENCY=DEEP_RESEARCH_SEARCH_CONCURRENCY:latest'
      - '--set-secrets=DEEP_RESEARCH_MODEL=DEEP_RESEARCH_MODEL:latest'
      - '--set-secrets=LANGGRAPH_RECURSION_LIMIT=LANGGRAPH_RECURSION_LIMIT:latest'
      - '--set-secrets=REDIS_STREAM_TTL_S_CHAT=REDIS_STREAM_TTL_S_CHAT:latest'
      - '--set-secrets=REDIS_STREAM_TTL_S_SEARCH=REDIS_STREAM_TTL_S_SEARCH:latest'
      - '--set-secrets=REDIS_STREAM_MAXLEN_CHAT=REDIS_STREAM_MAXLEN_CHAT:latest'
      - '--set-secrets=REDIS_STREAM_MAXLEN_SEARCH=REDIS_STREAM_MAXLEN_SEARCH:latest'
      - '--set-secrets=REDIS_STREAM_MAXLEN_SEARCH_MORE=REDIS_STREAM_MAXLEN_SEARCH_MORE:latest'
      - '--set-secrets=LLM_MODEL_GLOBAL_RPM=LLM_MODEL_GLOBAL_RPM:latest'
      - '--set-secrets=LLM_MODEL_GLOBAL_TPM=LLM_MODEL_GLOBAL_TPM:latest'
      - '--set-secrets=LLM_MODEL_GLOBAL_RPD=LLM_MODEL_GLOBAL_RPD:latest'
      - '--set-secrets=LLM_MODEL_GLOBAL_TPM_BURST=LLM_MODEL_GLOBAL_TPM_BURST:latest'
      - '--set-secrets=LLM_LIMIT_TIMEOUT_START_INTERACTIVE_S=LLM_LIMIT_TIMEOUT_START_INTERACTIVE_S:latest'
      - '--set-secrets=LLM_LIMIT_TIMEOUT_TOKENS_INTERACTIVE_S=LLM_LIMIT_TIMEOUT_TOKENS_INTERACTIVE_S:latest'
      - '--set-secrets=LLM_LIMIT_TIMEOUT_START_BACKGROUND_S=LLM_LIMIT_TIMEOUT_START_BACKGROUND_S:latest'
      - '--set-secrets=LLM_LIMIT_TIMEOUT_TOKENS_BACKGROUND_S=LLM_LIMIT_TIMEOUT_TOKENS_BACKGROUND_S:latest'
      - '--set-secrets=LLM_EST_COMPLETION_TOKENS_DEFAULT=LLM_EST_COMPLETION_TOKENS_DEFAULT:latest'
      # Standard Env vars we might want explicit
      - '--set-env-vars=GCP_PROJECT=$PROJECT_ID,GCLOUD_PROJECT=$PROJECT_ID'



options:
  logging: CLOUD_LOGGING_ONLY
